/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package body.mainScreenPack;

import body.mainScreenPack.Ults.TableController;
import body.mainScreenPack.Ults.TableControllerTarget;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.event.WindowAdapter;
import java.util.ArrayList;
import javax.swing.table.TableModel;

/**
 *
 * @author boginni
 */
public class ControllerHandlerPanel extends javax.swing.JPanel  implements TableControllerTarget {

     @Override
    public void doCellsUpdate() {

    }

    @Override
    public void doButtonsUpdate() { 
        uptadeButtons();
    }
    
    public interface TableHandlerPanelButtons{

        public void ckbFixActionPerformed(boolean curState);

        public void btnLastActionPerformed() ;

        public void btnNextActionPerformed();

        public void ckbShowDecActionPerformed(boolean curState);

    }

    private static ArrayList<TableHandlerPanelButtons> buttonListeners = new ArrayList<>();
    
    public static void addPanelControllerListener(TableHandlerPanelButtons target){
        buttonListeners.add(target);
    }

    
    /**
     * Creates new form ControllerHandlerPanel
     */
    public ControllerHandlerPanel() {
        initComponents();
        TableController.addTableControllerTarget(this);
    }
    
     void uptadeButtons() {

        boolean notNull = TableController.floatingTable != null;
        int curRow = 0, maxRow = 0;
        if (notNull) {
            curRow = TableController.getRow();
            maxRow = TableController.getCurrentLayer().getRowCount();
            lblCurLine.setText(String.valueOf(curRow));
            pgbRow.setValue(curRow);

            ckbFix.setSelected(false);
            ckbShowDec.setSelected(false);

        }


        btnNext.setEnabled(notNull && curRow < maxRow - 1);
        btnLast.setEnabled(notNull && curRow > 0);
        ckbFix.setEnabled(notNull);
        ckbShowDec.setEnabled(notNull);
    }
     
     public static WindowAdapter floatingTableClose;
    
    public void initTable() {

        int maxCol = Integer.parseInt(spnColCont.getValue().toString());
        int gapH = Integer.parseInt(spnHorizontalGap.getValue().toString());
        int gapV = Integer.parseInt(spnVerticalGap.getValue().toString());

        LayoutManager grid = new GridLayout(0, maxCol, gapH, gapV);

        TableController.createNewTable(0, grid);

        pgbRow.setMaximum(TableController.getCurrentLayer().getRowCount() - 1);
        ckbFixActionPerformed(null);
        ckbShowDecActionPerformed(null);
        uptadeButtons();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        lblCurLine = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnInitTable = new javax.swing.JButton();
        spnColCont = new javax.swing.JSpinner();
        final javax.swing.JLabel lblTitleLinha = new javax.swing.JLabel();
        ckbFix = new javax.swing.JCheckBox();
        ckbShowDec = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        spnVerticalGap = new javax.swing.JSpinner();
        final javax.swing.JLabel lblTitleLinha1 = new javax.swing.JLabel();
        spnHorizontalGap = new javax.swing.JSpinner();
        final javax.swing.JLabel lblTitleLinha2 = new javax.swing.JLabel();
        spnCurRow = new javax.swing.JSpinner();
        final javax.swing.JLabel lblTitleLinha3 = new javax.swing.JLabel();
        pgbRow = new javax.swing.JProgressBar();

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnLast.setText("<");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel3.add(btnLast, new java.awt.GridBagConstraints());

        lblCurLine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCurLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurLine.setText("000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 17;
        jPanel3.add(lblCurLine, gridBagConstraints);

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel3.add(btnNext, new java.awt.GridBagConstraints());

        btnInitTable.setText("Iniciar");
        btnInitTable.setPreferredSize(new java.awt.Dimension(85, 23));
        btnInitTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitTableActionPerformed(evt);
            }
        });

        spnColCont.setModel(new javax.swing.SpinnerNumberModel(8, 1, null, 1));

        lblTitleLinha.setText("Colunas Max por Linha");

        ckbFix.setText("Fixar na Tela");
        ckbFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbFixActionPerformed(evt);
            }
        });

        ckbShowDec.setText("Mostrar Decoração");
        ckbShowDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbShowDecActionPerformed(evt);
            }
        });

        spnVerticalGap.setModel(new javax.swing.SpinnerNumberModel(2, 1, null, 1));

        lblTitleLinha1.setText("VerticalGap");

        spnHorizontalGap.setModel(new javax.swing.SpinnerNumberModel(2, 1, null, 1));

        lblTitleLinha2.setText("HorizontalGap");

        spnCurRow.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblTitleLinha3.setText("Linha Inicial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInitTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnColCont, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleLinha, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addComponent(ckbFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbShowDec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnVerticalGap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleLinha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnHorizontalGap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleLinha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnCurRow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleLinha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgbRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInitTable, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(pgbRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnCurRow)
                    .addComponent(lblTitleLinha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnHorizontalGap)
                    .addComponent(lblTitleLinha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnVerticalGap)
                    .addComponent(lblTitleLinha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnColCont)
                    .addComponent(lblTitleLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbFix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbShowDec)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        buttonListeners.forEach(TableHandlerPanelButtons::btnLastActionPerformed);
        uptadeButtons();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        buttonListeners.forEach(TableHandlerPanelButtons::btnNextActionPerformed);
        uptadeButtons();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnInitTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitTableActionPerformed
        // TODO add your handling code here:
        initTable();
    }//GEN-LAST:event_btnInitTableActionPerformed

    private void ckbFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbFixActionPerformed
        // TODO add your handling code here:
        buttonListeners.forEach(t -> t.ckbFixActionPerformed(ckbFix.isSelected()));
    }//GEN-LAST:event_ckbFixActionPerformed

    private void ckbShowDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbShowDecActionPerformed
        // TODO add your handling code here:
        buttonListeners.forEach(t -> t.ckbShowDecActionPerformed(ckbShowDec.isSelected()));
    }//GEN-LAST:event_ckbShowDecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInitTable;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JCheckBox ckbFix;
    private javax.swing.JCheckBox ckbShowDec;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCurLine;
    private javax.swing.JProgressBar pgbRow;
    private javax.swing.JSpinner spnColCont;
    private javax.swing.JSpinner spnCurRow;
    private javax.swing.JSpinner spnHorizontalGap;
    private javax.swing.JSpinner spnVerticalGap;
    // End of variables declaration//GEN-END:variables
}
